### ISSUE TITLE
Send Requirements Specification to client

### ISSUE THREAD

**Issue by bl96** [TIS2019-FMFI/aurelium#18]

**Comment by pavelpetrovic** [comment]
Let's call the final "list of req" as "Requirements Specification".
I have read through your RS document and here is my feedback:

 - please leave out my name from the document, it is your project, I am only trying to make sure you are on the right track
 - since the document is in Slovak, I will respond in Slovak language as well :)
 - Vyznam dokumentu => Ucel dokumentu
 - prve dve casti dokumentu su fajn, akurat neviem odkial prislo 26Hz, preco nie napr. 25Hz? niektore kamery maju podla mna 25 Hz, ale mozno sa mylim.  
 - mali by ste pouzivat spravnu terminologiu. ked hovorime o detekcii, tak to len tvar najde, ak hovorime o rozpoznani, tak to zisti aj komu ta tvar patri
 (https://www.google.com/search?client=firefox-b-d&q=face+detection+vs+face+recognition)
teraz ku konkretnym poziadavkam:
3.1.1. vsetky poziadavky by mali byt formulovane ako nejaka hodnota, ktoru vyvijany system bude ponukat pouzivatelovi. su to poziadavky na softver, nie su to poziadavky na vyvojarov, na pouzivatelov a podobne. 3.1.1 nie je poziadavka na softver. je to obmedzenie. patri to do 2.5 alebo mozno 2.4.
3.1.5. aj gesta ocislujte, možnosť nastaviť dĺžku žmurknutia: ako? od-do v ms? aj kratke aj dlhe? poziadavky musia byt jednoznacne!
zatvorenie oka -> je to akcia alebo stav?
este mi napadli aj dalsie bonusy: skulenie (diva sa na nos), ocny povzdych (vyklopi oci hore)
(ale berte to len ako myslienky, nemusite to tam pridavat ak nechcete)
3.1.6. - prosim upresnite - prekryje to obraz kamery? bude to v strede? v rohu? ako dlho to tam zostane?
3.1.7. prosim upresnite - ako bude ta napoveda vyzerat? ako sa zobrazi? ako sa schova?
3.2.2. je mozne to nastavit do konfiguracneho suboru?
v porovnani s inymi skupinami je Vas dokument takmer celkom gramaticky spravny, chvalim! ale pred poslanim zadavatelovi to este raz skontrolujte, napr. "snímaní obraz" 
chyba mi:
 - informacia o tom, ci bude aplikacia responzivna vzhladom na rozlisenie displeja. tak trochu to vyplyva z toho, ze ma byt obraz maximalizovany na celu obrazovku, ale pre istotu to tam zdoraznite,
ze bude fungovat aj na roznych rozliseniach, lebo stale by sa to dalo pochopit aj tak, ze predpokladate nejake konkretne zafixovane rozlisenie displeja a na inych to nebude fungovat spravne

tiez by ma zaujimalo, ci doba medzi jednotlivymi ukonmi gesta bude definovatelna (ako interval) a tiez doba, po ktorej system zacne rozpoznavat nove gesto po tom, co nejake detekoval

a tiez by ma zaujimalo, ci gesta (postupnosti ukonov) budu natvrdo zadefinovane niekde vnutri kodu, alebo ci budu definovane v nejakom "konfiguracnom" subore, takze bude teoreticky mozne pridavat nove gesta - v druhom pripade to treba uviest v dokumente a myslim si, ze by to stalo za to tak urobit, ale je to vsetko samozrejme na Vasej dohode so zadavatelom.

zapracujte, prosim, tieto upravy a poslite mi novu verziu, aby som ju odobril na poslanie zadavatelovi, dakujem. zatial vyborna praca!

**Comment by nemsilajova** [comment]
V dokumente sú upravené pripomienky.

**Comment by martinavesela** [comment]
- [X] odstránenie mena mentora
- [X] účel dokumentu
- [X] oprava Hz na fps
- [X] rozpoznanie vs. detekcia
- [ ] 3.1.1
- [ ] 3.1.5
- [X] 3.1.6
- [ ] 3.1.7
- [ ] 3.2.2
- [ ] správanie aplikácie a vzhľadom ku rozlíšeniu
- [ ] interval medzi úkonmi gesta
- [ ] konfigurácia gest

**Comment by pavelpetrovic** [comment]
tensorflow-python, priklad

**Comment by pavelpetrovic** [comment]
dakujem za nove upravy v KP, priamo do zdielaneho dokumentu som Vam doplnil moje dalsie navrhy, ak ich akceptujete, poslite vysledny KP zadavatelovi a poziadajte ho, aby si ho dokladne prestudoval a napisal Vam, co treba upravit, lebo podla dohodnutej verzie uz system budete vyvijat. skontrolujte si KP pred tym este raz, ci je vsetko v poriadku. ak navrhy neakceptujete, tak ok, ale potom mi, prosim, este poslite novu verziu, alebo ich spolu prediskutujme. dakujem.

**Comment by pavelpetrovic** [comment]
dakujem za novu aktualizaciu KP, tesim sa, vsetko fajn, jedine treba este dotiahnut jednu vec a to zoznam ukonov. tak ako som Vam to navrhoval naposledy, boli ukony popisane, ako stavy. to znamena, gesto je postupnost stavov. napr. 
1. lave oko zatvorene
2. obe oci otvorene
3. obe oci zatvorene
4. lave oko zatvorene    (cize prave oko otvoril)
5. obe oci otvorene

vyhoda tohto zapisu je, ze je mozne robit viac kombinacii, aj take, ktore sa Vasim sposobom nedaju vyjadrit a vsetky zapisatelne kombinacie su korektne - daju sa dosiahnut.

v sposobe, ktory ste uviedli Vy, mi nie je celkom jasne, co sa tym mysli. ci napr. postupnost
1. zatvorenie laveho oka
2. zatvorenie oboch oci
znamena, ze  ma najskor zatvorit lave oko, potom ho otvorit a potom zatvorit obe oci naraz, alebo ci sa tym mysli, ze zatvori lave oko a potom aj prave, alebo ci obidve postupnosti akcii budu vyhovovat takemuto predpisu.
tiez vyvstava otazka, ci potom netreba pridat aj ukony na otvorenie, nielen na zatvorenie...

cize ak to chcete nechat ako akcie, ako to mate, tak prosim, v tom bode upresnit, ako tie ukony funguju, alebo to mozete este zmenit na tie stavy, ako som navrhoval v mojich upravach (hlasujem za tuto moznost, ale obe su fajn).

ked to dotiahnete, tak to rovno poslite zadavatelovi, 
este prosim v 3.10 operacny softver -> operačný systém 
(mysli sa tym Windows)
dakujem.

**Comment by martinavesela** [comment]
Podľa mňa otvorenie očí by malo byť ako oddeľovač medzi úkonmi. Keďže sú ľudia čo potrebujú veľmi často žmurkať, doba vyžadovaná na otvorené očí by mala byť minimálna.

**Comment by pavelpetrovic** [comment]
to je v poriadku, ak to chcete takto. 
vysvetlite to, prosim, v texte, aby to bolo jednoznacne.
dakujem.

**Comment by martinavesela** [comment]
U1 Zatvorenie oboch očí
U2 Zatvorenie ľavého oka
U3 Zatvorenie pravého oka
U4 Pohľad doľava
U5 Pohľad doprava
U6 Úsmev
U7 Vyplazený jazyk

Úkony U1-U3 budú oddelené otvorením očí; U4 a U5 pohľadom na displej/kameru; U6 a U7 zatvorenými ústami v neutrálnej pozícii.
