### ISSUE TITLE
stretnutie tento tyzden

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2019-FMFI/aurelium#27]
aktualne je dolezite, aby ste komunikovali v time o vsetkom velmi intenzivne aj viackrat tyzdenne a aby vsetci clenovia timu rozumeli a boli stotozneni so vsetkym, co sa na projekte deje.

preto sa znovu stretnite na timovom stretnuti este tento tyzden, vytvorte z neho aj zapisnicu, dorieste fungovanie celej aplikacie - co presne ktora metoda bude robit a ako system bude fungovat.

nie je mozne, aby ste v tejto faze projektu stale nemali v zakladnych veciach jednotny pohlad na system, tieto nezrovnalosti nie je mozne riesit na nasich stretnutiach, lebo potom z nich odchadzate skor ako skoncia, ako to bolo dnes.

takze, zacat treba tym, ze ti, ktori vedia ako presne funguju kniznice na detekciu to ostatnym vysvetlia, od toho sa odrazite a vymyslite ako funguje cely system, zachytite to v triednom diagrame a co najrovnomernejsie si rozdelite implementacnu pracu medzi sebou.

**Comment by martinavesela** [comment]
Práca na návrhu

- [ ] OpenCV funkcie - Miro, Matej
- [ ] NumPy funkcie - Miro, Matej
- [ ] GazeTracking funkcie - Miro, Matej
- [ ] CMake funkcie - Miro, Matej
- [ ] Triedny diagram urobiť - Ivana, Martina
- [ ] Schválenie triedneho diagramu - Petrovič
- [ ] Opraviť diagram komponentov - Miro, Martina
- [ ] Schválenie diagramu komponentov - Petrovič
- [ ] Konfiguračný súbor - všetci
- [ ] Rozdelenie práce - všetci

**Comment by martinavesela** [comment]
![aurelium_class_diagram](https://user-images.githubusercontent.com/47821741/69825189-b1cbff80-120e-11ea-92a1-2647fb103bc2.png)

**Comment by martinavesela** [comment]
![aurelium_class_diagram](https://user-images.githubusercontent.com/47821741/69826630-513fc100-1214-11ea-9fca-18bcf55d3f69.png)

**Comment by bl96** [comment]
openCV funkcie
cv2.VideoCapture(int:numberOfCamera(starting with 0))
cv2.putText(frame:frame,string:text) -> print text
cv2.rectangle(frame:frame,tuple:coords,tuple:coords,color:color,int:width) -> print rectangle on given frame with given coords
cv2.imshow(string:name,frame:frame) -> display window frame with given image
cv2.waitKey(int:number)==int:number -> wait until key is pressed, otherwise do something
cv2.destroyAllWindows() -> destroy all created windows frames
cv2.resize(frame:frame,tuple:size) -> resize image to given size
camera.read() -> get a new frame from camera
camera.get(property:prop) -> show fps(cv2.CAP_PROP_FPS) or other properties
camera.isOpened() -> if camera is active

**Comment by bl96** [comment]
Nejasnosti v názoroch sa pokúsime čo najrýchlejšie vyriešiť a zjednotiť. Práca bude rozdelená v issues, kde si bude môcť každý pozrieť čo má urobiť. Podľa zápisnice sa bude vedieť, že ktorá úloha sa momentálny týždeň rieši každým členom tímu.
